/**
 * Filing generated bytes as a new version of an existing document.
 *
 * The PDF editor never overwrites what it was given. Every export — burned
 * markup, a page deletion, a rotation — lands as the next version in the
 * document's chain, so the original stays exactly as uploaded and the history
 * shows what changed and when. That mirrors the first ground rule of the
 * Cowork PDF skill ("never modify the original file"), and it is the reason
 * the editor can be used on a signed contract without risk.
 *
 * NOT a `"use server"` module. Every export of one becomes a POST endpoint
 * reachable from a browser, and this function writes documents without doing
 * its own authorization — it trusts the caller to have done it. Keeping it as
 * a plain module means it cannot be called from outside. Same reasoning as
 * `lib/integrations/fireflies-sync.ts`.
 */

import { desc, eq, sql } from "drizzle-orm";
import { documents } from "@/lib/db/schema";
import { withEngagementContext } from "@/lib/db/tenant";
import { uploadDocumentBlob } from "@/lib/storage/blobs";

export type NewVersionInput = {
  callerOrgId: string;
  callerRole: string;
  engagementId: string;
  /** The document the new version descends from. */
  parentDocumentId: string;
  bytes: Uint8Array;
  filename: string;
  uploaderUserProfileId: string;
};

export type NewVersion = {
  id: string;
  version: number;
  filename: string;
};

export async function fileNewDocumentVersion(
  input: NewVersionInput,
): Promise<NewVersion> {
  const {
    callerOrgId,
    callerRole,
    engagementId,
    parentDocumentId,
    bytes,
    filename,
    uploaderUserProfileId,
  } = input;

  // Bind first, purely to learn which org owns the engagement — the blob key
  // is prefixed with it, and getting that wrong would file the bytes under
  // the wrong tenant's prefix.
  const boundOrgId = await withEngagementContext(
    callerOrgId,
    callerRole,
    engagementId,
    async (_tx, orgId) => orgId,
  );

  // `uploadDocumentBlob` takes a Web File, which Node 20 provides globally.
  // Copy into a fresh ArrayBuffer: a Uint8Array from pdf-lib can be a view
  // onto a larger pooled buffer, and handing the raw buffer to File would
  // write out neighbouring bytes as well.
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  const file = new File([copy], filename, { type: "application/pdf" });

  const upload = await uploadDocumentBlob(boundOrgId, file);

  return await withEngagementContext(
    callerOrgId,
    callerRole,
    engagementId,
    async (tx, orgId) => {
      const [parent] = await tx
        .select({
          id: documents.id,
          parentDocumentId: documents.parentDocumentId,
        })
        .from(documents)
        .where(eq(documents.id, parentDocumentId))
        .limit(1);
      if (!parent) throw new Error("Original document not found.");

      // Versions point at the chain root, not at each other, matching
      // `uploadDocumentVersion` from Phase 3.11. Chain depth stays 1.
      const chainRoot = parent.parentDocumentId ?? parent.id;

      const [latest] = await tx
        .select({ version: documents.version })
        .from(documents)
        .where(
          sql`(documents.id = ${chainRoot} OR documents.parent_document_id = ${chainRoot})`,
        )
        .orderBy(desc(documents.version))
        .limit(1);
      const nextVersion = (Number(latest?.version) || 1) + 1;

      const [row] = await tx
        .insert(documents)
        .values({
          id: upload.documentId,
          orgId,
          engagementId,
          blobKey: upload.blobKey,
          originalFilename: upload.filename,
          fileType: "application/pdf",
          sizeBytes: upload.sizeBytes,
          uploaderUserProfileId,
          version: nextVersion,
          parentDocumentId: chainRoot,
        })
        .returning({
          id: documents.id,
          version: documents.version,
          originalFilename: documents.originalFilename,
        });

      return {
        id: row.id,
        version: Number(row.version),
        filename: row.originalFilename,
      };
    },
  );
}

/**
 * Output filename for an edited copy.
 *
 * Keeps the original stem and appends what was done, so a folder listing
 * reads as a history rather than as five files with the same name. Mirrors
 * the Cowork skill's naming rule for quick utility jobs.
 */
export function editedFilename(original: string, suffix: string): string {
  const stem = original.replace(/\.pdf$/i, "");
  return `${stem} - ${suffix}.pdf`;
}
