/**
 * How a stored file should be described and arranged on screen.
 *
 * Pure — no database, no server imports — so the client components that
 * render document lists can use the same rules the server does.
 *
 * **The problem this solves.** An agreement exists as two files: the copy
 * that was sent out, and the executed copy that came back. They carry
 * almost the same name and land days apart, so in a flat, newest-first
 * list they read as a duplicate and a stray. Someone tidying up deletes
 * one. On KS Developments that would have destroyed a real executed
 * contract, and the only thing standing between the panel and that
 * outcome was the operator recognising the pair by eye.
 *
 * So the pair is presented as what it is: one agreement, with its source
 * and its signed copy underneath it, labelled.
 */

import type { DocumentOrigin } from "@/lib/db/schema";

/** Which half of a signing envelope a document is. */
export type EnvelopeRole = "source" | "signed";

export type PresentableDocument = {
  id: string;
  filename: string;
  fileType: string;
  sizeBytes: number;
  uploaderName: string | null;
  createdAt: Date;
  origin: DocumentOrigin;
  envelopeId: string | null;
  envelopeSubject: string | null;
  envelopeStatus: string | null;
  envelopeRole: EnvelopeRole | null;
};

/**
 * A display name that says what the file IS, without renaming it on disk.
 *
 * Renaming the stored file was the other option and was rejected: the
 * name is what the client sees when they download it, "Business building
 * agreement.pdf" is the right thing to arrive in their inbox, and a
 * rename would need a migration that could only reach rows we knew
 * about. The label is a presentation concern, so it lives in
 * presentation.
 */
export function documentDisplayName(doc: PresentableDocument): string {
  if (doc.envelopeRole === "source") {
    // The unsigned copy. Says "sent for signature", not "unsigned" —
    // an operator scanning the list needs to know it is half of a pair,
    // not that something is missing.
    return `${stripExtension(doc.filename)} (sent for signature)`;
  }
  if (doc.envelopeRole === "signed") {
    return `${stripExtension(doc.filename).replace(/\s*[—–-]\s*signed$/i, "")} — signed`;
  }
  return doc.filename;
}

function stripExtension(filename: string): string {
  return filename.replace(/\.[A-Za-z0-9]{1,6}$/, "");
}

/**
 * Where the file came from, in words.
 *
 * The old caption printed the uploader's name and fell back to the
 * literal "The Climb" when there wasn't one — which mislabelled every
 * signed agreement, because the signing flow files documents with no
 * person attached. This reads `origin`, which is recorded at write time.
 */
export function documentProvenance(doc: PresentableDocument): string {
  switch (doc.origin) {
    case "signed":
      return "Generated by the signing flow";
    case "the_climb":
      return "The Climb";
    case "upload":
    default:
      return doc.uploaderName ? `Uploaded by ${doc.uploaderName}` : "Uploaded";
  }
}

/** A short, human status for the agreement heading. */
export function envelopeStatusLabel(status: string | null): string {
  switch (status) {
    case "completed":
      return "Signed";
    case "in_progress":
      return "Out for signature";
    case "voided":
      return "Voided";
    case "draft":
      return "Draft";
    default:
      return status ?? "";
  }
}

export type DocumentGroup =
  | {
      kind: "agreement";
      envelopeId: string;
      subject: string;
      status: string | null;
      /** Newest first within the group, so the signed copy leads. */
      documents: PresentableDocument[];
    }
  | { kind: "loose"; document: PresentableDocument };

/**
 * Arrange a flat document list into agreements-with-their-parts plus
 * everything else, newest first.
 *
 * An agreement group is dated by its NEWEST member so a freshly signed
 * contract rises to the top of the panel, rather than sinking to wherever
 * the source PDF was uploaded days earlier.
 */
export function groupDocuments(docs: PresentableDocument[]): DocumentGroup[] {
  const byEnvelope = new Map<string, PresentableDocument[]>();
  const loose: PresentableDocument[] = [];

  for (const d of docs) {
    if (d.envelopeId) {
      const bucket = byEnvelope.get(d.envelopeId);
      if (bucket) bucket.push(d);
      else byEnvelope.set(d.envelopeId, [d]);
    } else {
      loose.push(d);
    }
  }

  const groups: { at: number; group: DocumentGroup }[] = [];

  // Array.from rather than iterating the Map directly — the project's
  // tsconfig target predates downlevel Map iteration.
  for (const [envelopeId, members] of Array.from(byEnvelope.entries())) {
    // A group of one is still a group — an agreement out for signature
    // has only its source copy, and it should already be labelled as
    // such rather than sitting loose and then re-arranging once it
    // comes back signed.
    members.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
    const newest = members[0];
    groups.push({
      at: newest.createdAt.getTime(),
      group: {
        kind: "agreement",
        envelopeId,
        subject: newest.envelopeSubject ?? "Agreement",
        status: newest.envelopeStatus,
        documents: members,
      },
    });
  }

  for (const d of loose) {
    groups.push({ at: d.createdAt.getTime(), group: { kind: "loose", document: d } });
  }

  groups.sort((a, b) => b.at - a.at);
  return groups.map((g) => g.group);
}
